### ISSUE TITLE
GSM8K performance difference issue

### ISSUE THREAD

**Issue by allanj** [madaan/self-refine#11]
In the appendix, the original PAL with ChatGPT is around 74%.
<img width="737" alt="image" src="https://github.com/madaan/self-refine/assets/3351187/68e25903-9ba1-4fcd-a50d-215b0b2c1639">

But how come the initial accuracy is only 71% in self-refine, I was expecting the initial should be the same?
<img width="899" alt="image" src="https://github.com/madaan/self-refine/assets/3351187/df77263b-f1f5-44de-9eec-143a7402158a">

**Comment by madaan** [comment]
Thanks for pointing this out. The results in Figure 14 use code-davinci-002 (codex), which match the numbers reported in PaL (72%). We will clarify this in the next update.
