### ISSUE TITLE
CommonGen-Hard dataset

### ISSUE THREAD

**Issue by lifu-tu** [madaan/self-refine#3]
Will you release the CommonGen-Hard dataset soon? It looks like that it has 20-30 concepts for each sentence. Very curious about this dataset.

**Comment by madaan** [comment]
Sorry, the dataset was missing! Thanks for pointing this out. I've added it [here](https://github.com/madaan/self-refine/tree/main/data/prompt/commongen). We will also add the other datasets/results on new models over the next few days.
