### ISSUE TITLE
Codex discontinued

### ISSUE THREAD

**Issue by hideodeo** [madaan/self-refine#4]
Hello. For code-related tasks, do you plan to update your code to replace the Codex with another model? Do you have a suggestion for the alternative model & do you plan to push the updated code?

**Comment by madaan** [comment]
Hi @hideodeo, we are working on Self-Refine + text-davinci-003, ChatGPT, and GPT-4. The results so far are quite promising, and we will release the code and results soon.

**Comment by hideodeo** [comment]
Sounds great! Looking forward to seeing results

**Comment by hideodeo** [comment]
Hi @madaan 
I'd like to quickly try ChatGPT with gsm/run.py. Can I simply change 
`CODEX = "code-davinci-002"`
to
`CODEX = "gpt-3.5-turbo" `
in gsm/run.py?

I'm wondering if it requires more modifications because I remember the way to feed examplers is different in gpt-3.5-turbo compared to code-davinci-002 (e.g. specifying "role"). Thank you!

**Comment by madaan** [comment]
Yes! If you update https://github.com/reasoning-machines/prompt-lib/tree/main/prompt_lib it should just work. Prompt-lib now supports chat models.

**Comment by hideodeo** [comment]
Nice! Thank you for info!
