### ISSUE TITLE
Code optimization

### ISSUE THREAD

**Issue by juny116** [madaan/self-refine#5]
Hello,I am really interested in your fine work and trying to reproduce the results!

Can you share the prompts and examples for the code optimization?
I am having hard time reproducing the code optimization results.
I have an additional question regarding code optimization in your paper. Specifically, I'm interested in how you calculated the percentage of programs that were optimized. When reproducing the results, I noticed that some codes performed worse, while others actually showed improvement.

**Comment by madaan** [comment]
Hi @juny116 , sorry about the late response.

The [prompts](https://github.com/madaan/self-refine/tree/main/data/prompt/pie) and the [code](https://github.com/madaan/self-refine/tree/main/src/pie) has been added. For evaluation, you'll need to follow evaluation setup [here](https://github.com/madaan/pie-perf#evaluating-your-method).
