### ISSUE TITLE
Releasing the Yelp Dataset

### ISSUE THREAD

**Issue by mingkaid** [madaan/self-refine#8]
Amazing work! We are interested in building on this work. Are there any plans for releasing the long-form sentiment reversal Yelp datatset in this work? Thanks!

**Comment by madaan** [comment]
[Done!](https://github.com/madaan/self-refine/commit/daafd0c4e0538ba7091e2c3bebffd5aba156c0d2)

**Comment by mingkaid** [comment]
Thanks Madaan! This is super helpful. Would you also be able to share the evaluation dataset for Acronym Generation? We are running some preliminary experiments, and are looking for a task that's shorter and faster to iterate over.

**Comment by madaan** [comment]
Done [here](https://github.com/madaan/self-refine/commit/ebf5a73a078512ec62b0268b993a720550faa348)!
